ALTER TYPE "AdminAuditAction" ADD VALUE 'PRODUCT_CREATED';
ALTER TYPE "AdminAuditAction" ADD VALUE 'PRODUCT_UPDATED';
ALTER TYPE "AdminAuditAction" ADD VALUE 'PRODUCT_DELETED';
ALTER TYPE "AdminAuditAction" ADD VALUE 'PRODUCT_STATE_CHANGED';
ALTER TYPE "AdminAuditAction" ADD VALUE 'INVENTORY_UPDATED';
