"use client";

import Image from "next/image";
import { useActionState, useState } from "react";
import { categoryStateAction, deleteCategoryAction, deleteSubcategoryAction, moveCategoryAction, moveSubcategoryAction, saveCategoryAction, saveSubcategoryAction, subcategoryStateAction } from "@/actions/categories";
import type { CategoryAdminDto, SubcategoryAdminDto } from "@/data/categories";
import { initialMutationState } from "@/types/mutation-state";

const input = "admin-input";
const label = "admin-label";
function Feedback({ state }: { state: typeof initialMutationState }) { return state.message ? <p className={state.status === "error" ? "text-sm text-red-700" : "text-sm text-emerald-700"} role="status">{state.message}</p> : null; }
function slugify(value: string) { return value.toLowerCase().trim().replace(/&/g, "and").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, ""); }

function CategoryForm({ category }: { category?: CategoryAdminDto }) {
  const [state, action, pending] = useActionState(saveCategoryAction, initialMutationState);
  const [name, setName] = useState(category?.name ?? ""); const [slug, setSlug] = useState(category?.slug ?? ""); const [manual, setManual] = useState(Boolean(category));
  return <form action={action} encType="multipart/form-data" className="grid gap-4"><input type="hidden" name="id" value={category?.id ?? ""} /><div className="grid gap-4 md:grid-cols-2"><label className={label}>Name<input className={input} name="name" required maxLength={80} value={name} onChange={(event) => { setName(event.target.value); if (!manual) setSlug(slugify(event.target.value)); }} /></label><label className={label}>Slug<input className={input} name="slug" required maxLength={100} value={slug} onChange={(event) => { setSlug(slugify(event.target.value)); setManual(true); }} /></label></div><label className={label}>Description <span className="font-normal text-admin-muted">Optional</span><textarea className={`${input} min-h-24 py-3`} name="description" maxLength={1000} defaultValue={category?.description ?? ""} /></label><div className="grid gap-4 md:grid-cols-2"><label className={label}>Tile image <span className="font-normal text-admin-muted">Optional, up to 5 MB</span><input className={input} type="file" name="image" accept="image/jpeg,image/png,image/webp" />{category?.imageUrl ? <span className="flex min-h-11 items-center gap-2 font-normal"><input type="checkbox" name="removeImage" /> Remove current tile image</span> : null}</label><label className={label}>Banner image <span className="font-normal text-admin-muted">Optional, up to 5 MB</span><input className={input} type="file" name="bannerImage" accept="image/jpeg,image/png,image/webp" />{category?.bannerImageUrl ? <span className="flex min-h-11 items-center gap-2 font-normal"><input type="checkbox" name="removeBannerImage" /> Remove current banner image</span> : null}</label></div><Feedback state={state} /><button className="admin-button justify-self-start" disabled={pending}>{pending ? "Saving…" : category ? "Save category" : "Create category"}</button></form>;
}

function Action({ action, id, fields, children, confirm }: { action: (state: typeof initialMutationState, data: FormData) => Promise<typeof initialMutationState>; id: string; fields?: Record<string, string>; children: React.ReactNode; confirm?: string }) {
  const [state, formAction, pending] = useActionState(action, initialMutationState);
  return <form action={formAction} onSubmit={(event) => { if (confirm && !window.confirm(confirm)) event.preventDefault(); }}><input type="hidden" name="id" value={id} />{Object.entries(fields ?? {}).map(([name, value]) => <input key={name} type="hidden" name={name} value={value} />)}<button className="admin-action min-h-11" disabled={pending}>{pending ? "Working…" : children}</button>{state.status === "error" ? <p className="mt-1 max-w-56 text-xs text-red-700" role="alert">{state.message}</p> : null}</form>;
}

function SubcategoryForm({ categoryId, subcategory }: { categoryId: string; subcategory?: SubcategoryAdminDto }) {
  const [state, action, pending] = useActionState(saveSubcategoryAction, initialMutationState);
  const [name, setName] = useState(subcategory?.name ?? ""); const [slug, setSlug] = useState(subcategory?.slug ?? ""); const [manual, setManual] = useState(Boolean(subcategory));
  return <form action={action} className="grid gap-3 rounded-md border border-admin-line bg-admin-soft p-4"><input type="hidden" name="id" value={subcategory?.id ?? ""} /><input type="hidden" name="categoryId" value={categoryId} /><div className="grid gap-3 sm:grid-cols-2"><label className={label}>Name<input className={input} name="name" required maxLength={80} value={name} onChange={(event) => { setName(event.target.value); if (!manual) setSlug(slugify(event.target.value)); }} /></label><label className={label}>Slug<input className={input} name="slug" required maxLength={100} value={slug} onChange={(event) => { setSlug(slugify(event.target.value)); setManual(true); }} /></label></div><label className={label}>Description <span className="font-normal text-admin-muted">Optional</span><textarea className={`${input} min-h-20 py-3`} name="description" maxLength={1000} defaultValue={subcategory?.description ?? ""} /></label><Feedback state={state} /><button className="admin-button justify-self-start" disabled={pending}>{pending ? "Saving…" : subcategory ? "Save subcategory" : "Add subcategory"}</button></form>;
}

export function CategoryManager({ categories }: { categories: CategoryAdminDto[] }) {
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  return <div className="grid gap-6"><section className="admin-panel"><h2 className="admin-section-title">Add category</h2><p className="admin-help mb-5">Categories and subcategories drive the storefront navigation and filters.</p><CategoryForm /></section>{categories.length ? categories.map((category, index) => <details className="admin-panel" key={category.id}><summary className="flex cursor-pointer list-none flex-wrap items-center gap-4"><div className="relative size-16 shrink-0 overflow-hidden rounded bg-admin-soft">{category.imageUrl ? <Image src={category.imageUrl} alt="" fill sizes="64px" className="object-cover" /> : null}</div><div className="min-w-0 flex-1"><h2 className="font-bold text-admin-ink">{category.name}</h2><p className="text-sm text-admin-muted">/{category.slug} · {category.productCount} products · {category.subcategories.length} subcategories · {category.isActive ? "Active" : "Hidden"}</p></div><span className="admin-action">Manage</span></summary><div className="mt-6 grid gap-6 border-t border-admin-line pt-6"><CategoryForm category={category} /><div className="flex flex-wrap gap-2"><Action action={categoryStateAction} id={category.id} fields={{ value: String(!category.isActive) }}>{category.isActive ? "Hide" : "Activate"}</Action><Action action={moveCategoryAction} id={category.id} fields={{ direction: "up" }}>Move up</Action><Action action={moveCategoryAction} id={category.id} fields={{ direction: "down" }}>Move down</Action><Action action={deleteCategoryAction} id={category.id} confirm={`Delete ${category.name}? Only empty categories can be deleted.`}>Delete</Action></div><section><h3 className="mb-3 font-bold text-admin-ink">Subcategories</h3><div className="grid gap-4">{category.subcategories.map((subcategory) => <div key={subcategory.id}><SubcategoryForm categoryId={category.id} subcategory={subcategory} /><div className="mt-2 flex flex-wrap gap-2"><Action action={subcategoryStateAction} id={subcategory.id} fields={{ value: String(!subcategory.isActive) }}>{subcategory.isActive ? "Hide" : "Activate"}</Action><Action action={moveSubcategoryAction} id={subcategory.id} fields={{ direction: "up" }}>Move up</Action><Action action={moveSubcategoryAction} id={subcategory.id} fields={{ direction: "down" }}>Move down</Action><Action action={deleteSubcategoryAction} id={subcategory.id} confirm={`Delete ${subcategory.name}? Only unused subcategories can be deleted.`}>Delete</Action></div></div>)}<SubcategoryForm categoryId={category.id} /></div></section></div></details>) : <div className="admin-panel py-12 text-center text-admin-muted">No categories yet. Create the first real category above.</div>}</div>;
}
