"use client";

import Image from "next/image";
import { useActionState, useState } from "react";
import { saveContentBlockAction } from "@/actions/cms";
import { cmsBlockDefinitions, type CmsBlockValue } from "@/types/cms";
import { initialMutationState, type MutationState } from "@/types/mutation-state";

type Block = { id: string; area: string; key: string; content: CmsBlockValue };
export function ContentEditor({ blocks }: { blocks: Block[] }) { return <div className="grid gap-8"><EditorGroup title="Website sections" description="Edit approved homepage and brand content without changing source code."><div className="grid gap-4">{cmsBlockDefinitions.map((definition) => <ContentForm key={`${definition.area}:${definition.key}`} definition={definition} value={blocks.find((item) => item.area === definition.area && item.key === definition.key)?.content} />)}</div></EditorGroup></div>; }
function ContentForm({ definition, value }: { definition: (typeof cmsBlockDefinitions)[number]; value?: CmsBlockValue }) {
  const [state, action, pending] = useActionState(saveContentBlockAction, initialMutationState); const [preview, setPreview] = useState(value?.imageUrl ?? "");
  return <details className="admin-panel" open={definition.key === "hero"}><summary className="cursor-pointer font-bold text-admin-ink">{definition.label}<span className="ml-2 text-xs font-normal uppercase tracking-wide text-admin-muted">{definition.area}</span></summary><form action={action} className="mt-5 grid gap-4"><input type="hidden" name="area" value={definition.area} /><input type="hidden" name="key" value={definition.key} />{definition.fields.map(([name, label, multiline]) => <label className="admin-label" key={name}>{label}{multiline ? <textarea className="admin-input min-h-28 py-3" name={`field:${name}`} defaultValue={value?.fields[name] ?? ""} /> : <input className="admin-input" name={`field:${name}`} defaultValue={value?.fields[name] ?? ""} />}</label>)}{"image" in definition && definition.image ? <div className="grid gap-3 sm:grid-cols-[150px_1fr]"><div className="relative aspect-[4/3] overflow-hidden rounded border border-admin-line bg-admin-soft">{preview ? <Image src={preview} alt="Section preview" fill sizes="150px" className="object-cover" /> : <span className="grid h-full place-items-center text-xs text-admin-muted">No image</span>}</div><label className="admin-label">Section image<input className="admin-input" name="image" type="file" accept="image/jpeg,image/png,image/webp" onChange={(event) => { const selected = event.target.files?.[0]; if (selected) setPreview(URL.createObjectURL(selected)); }} />{value?.imageUrl ? <span className="flex items-center gap-2 font-normal"><input name="removeImage" type="checkbox" onChange={(event) => setPreview(event.target.checked ? "" : value.imageUrl ?? "")} /> Remove current image</span> : null}</label></div> : null}<Feedback state={state} /><button className="admin-button justify-self-start" disabled={pending}>{pending ? "Saving…" : `Save ${definition.label}`}</button></form></details>;
}
function EditorGroup({ title, description, children }: { title: string; description: string; children: React.ReactNode }) { return <section><h2 className="text-xl font-bold text-admin-ink">{title}</h2><p className="mb-4 mt-1 text-sm text-admin-muted">{description}</p>{children}</section>; }
function Feedback({ state }: { state: MutationState }) { return state.message ? <p role="status" className={`rounded border px-3 py-2 text-sm ${state.status === "success" ? "border-emerald-300 bg-emerald-50 text-emerald-800" : "border-red-300 bg-red-50 text-red-800"}`}>{state.message}</p> : null; }
