"use client";

import Image from "next/image";
import { useActionState, useState } from "react";
import { saveAnnouncementAction, saveContentBlockAction, savePolicyAction } from "@/actions/cms";
import { cmsBlockDefinitions, policyDefinitions, type CmsBlockValue } from "@/types/cms";
import { initialMutationState, type MutationState } from "@/types/mutation-state";

type Block = { id: string; area: string; key: string; content: CmsBlockValue };
type Policy = { slug: string; title: string; content: string; isPublished: boolean; seoTitle: string | null; seoDescription: string | null };
type Announcement = { id: string; text: string; linkUrl: string | null; linkLabel: string | null; background: string; enabled: boolean; startAt: string | null; endAt: string | null } | null;

export function ContentEditor({ blocks, policies, announcement }: { blocks: Block[]; policies: Policy[]; announcement: Announcement }) {
  return <div className="grid gap-8"><EditorGroup title="Announcement bar" description="Enabled announcements are evaluated against their optional UTC schedule at request time."><AnnouncementForm value={announcement} /></EditorGroup><EditorGroup title="Website sections" description="Empty optional copy remains absent; it is never replaced with invented text."><div className="grid gap-4">{cmsBlockDefinitions.map((definition) => <ContentForm key={`${definition.area}:${definition.key}`} definition={definition} value={blocks.find((item) => item.area === definition.area && item.key === definition.key)?.content} />)}</div></EditorGroup><EditorGroup title="Policy and help pages" description="Content is stored and rendered as plain text. Raw HTML is never executed."><div className="grid gap-4">{policyDefinitions.map(([slug, defaultTitle]) => <PolicyForm key={slug} slug={slug} defaultTitle={defaultTitle} value={policies.find((item) => item.slug === slug)} />)}</div></EditorGroup></div>;
}

function ContentForm({ definition, value }: { definition: (typeof cmsBlockDefinitions)[number]; value?: CmsBlockValue }) {
  const [state, action, pending] = useActionState(saveContentBlockAction, initialMutationState); const [preview, setPreview] = useState(value?.imageUrl ?? "");
  return <details className="admin-panel" open={definition.key === "hero"}><summary className="cursor-pointer font-bold text-admin-ink">{definition.label}<span className="ml-2 text-xs font-normal uppercase tracking-wide text-admin-muted">{definition.area}</span></summary><form action={action} encType="multipart/form-data" className="mt-5 grid gap-4"><input type="hidden" name="area" value={definition.area} /><input type="hidden" name="key" value={definition.key} />{definition.fields.map(([name, label, multiline]) => <label className="admin-label" key={name}>{label}{multiline ? <textarea className="admin-input min-h-28 py-3" name={`field:${name}`} defaultValue={value?.fields[name] ?? ""} /> : <input className="admin-input" name={`field:${name}`} defaultValue={value?.fields[name] ?? ""} />}</label>)}{"image" in definition && definition.image ? <div className="grid gap-3 sm:grid-cols-[150px_1fr]"><div className="relative aspect-[4/3] overflow-hidden rounded border border-admin-line bg-admin-soft">{preview ? <Image src={preview} alt="Hero preview" fill sizes="150px" className="object-cover" /> : <span className="grid h-full place-items-center text-xs text-admin-muted">No hero image</span>}</div><label className="admin-label">Hero image<input className="admin-input" name="image" type="file" accept="image/jpeg,image/png,image/webp" onChange={(event) => { const selected = event.target.files?.[0]; if (selected) setPreview(URL.createObjectURL(selected)); }} />{value?.imageUrl ? <span className="flex items-center gap-2 font-normal"><input name="removeImage" type="checkbox" onChange={(event) => setPreview(event.target.checked ? "" : value.imageUrl ?? "")} /> Remove current image</span> : null}</label></div> : null}<Feedback state={state} /><button className="admin-button justify-self-start" disabled={pending}>{pending ? "Saving…" : `Save ${definition.label}`}</button></form></details>;
}

function PolicyForm({ slug, defaultTitle, value }: { slug: (typeof policyDefinitions)[number][0]; defaultTitle: string; value?: Policy }) {
  const [state, action, pending] = useActionState(savePolicyAction, initialMutationState);
  return <details className="admin-panel"><summary className="cursor-pointer font-bold text-admin-ink">{value?.title ?? defaultTitle}{value?.isPublished ? <span className="ml-2 rounded-full bg-emerald-100 px-2 py-1 text-[10px] uppercase text-emerald-800">Published</span> : <span className="ml-2 rounded-full bg-admin-soft px-2 py-1 text-[10px] uppercase text-admin-muted">Draft</span>}</summary><form action={action} className="mt-5 grid gap-4"><input type="hidden" name="slug" value={slug} /><label className="admin-label">Title<input className="admin-input" name="title" defaultValue={value?.title ?? defaultTitle} required /></label><label className="admin-label">Page content<textarea className="admin-input min-h-72 py-3" name="content" defaultValue={value?.content ?? ""} placeholder="Enter approved business or policy information. Leave as draft until complete." /></label><div className="grid gap-4 md:grid-cols-2"><label className="admin-label">SEO title<input className="admin-input" name="seoTitle" defaultValue={value?.seoTitle ?? ""} /></label><label className="admin-label">SEO description<textarea className="admin-input min-h-20 py-3" name="seoDescription" defaultValue={value?.seoDescription ?? ""} /></label></div><label className="flex items-center gap-2 text-sm font-semibold text-admin-ink"><input type="checkbox" name="isPublished" defaultChecked={value?.isPublished} /> Published</label><Feedback state={state} /><button className="admin-button justify-self-start" disabled={pending}>{pending ? "Saving…" : "Save page"}</button></form></details>;
}

function AnnouncementForm({ value }: { value: Announcement }) {
  const [state, action, pending] = useActionState(saveAnnouncementAction, initialMutationState);
  const date = (input: string | null | undefined) => input ? new Date(input).toISOString().slice(0, 16) : "";
  return <form action={action} className="admin-panel grid gap-4"><input type="hidden" name="id" value={value?.id ?? ""} /><label className="admin-label">Text<input className="admin-input" name="text" defaultValue={value?.text ?? ""} required /></label><div className="grid gap-4 md:grid-cols-2"><label className="admin-label">Link label<input className="admin-input" name="linkLabel" defaultValue={value?.linkLabel ?? ""} /></label><label className="admin-label">Link URL<input className="admin-input" name="linkUrl" defaultValue={value?.linkUrl ?? ""} placeholder="/shop or https://…" /></label><label className="admin-label">Background<select className="admin-input" name="background" defaultValue={value?.background ?? "DARK"}><option value="DARK">Dark</option><option value="GOLD">Gold</option><option value="CRITICAL">Critical red</option></select></label><label className="admin-label">Starts (UTC)<input className="admin-input" type="datetime-local" name="startAt" defaultValue={date(value?.startAt)} /></label><label className="admin-label">Ends (UTC)<input className="admin-input" type="datetime-local" name="endAt" defaultValue={date(value?.endAt)} /></label></div><label className="flex items-center gap-2 text-sm font-semibold text-admin-ink"><input type="checkbox" name="enabled" defaultChecked={value?.enabled} /> Enabled</label><Feedback state={state} /><button className="admin-button justify-self-start" disabled={pending}>{pending ? "Saving…" : "Save announcement"}</button></form>;
}

function EditorGroup({ title, description, children }: { title: string; description: string; children: React.ReactNode }) { return <section><h2 className="text-xl font-bold text-admin-ink">{title}</h2><p className="mb-4 mt-1 text-sm text-admin-muted">{description}</p>{children}</section>; }
function Feedback({ state }: { state: MutationState }) { return state.message ? <p role="status" className={`rounded border px-3 py-2 text-sm ${state.status === "success" ? "border-emerald-300 bg-emerald-50 text-emerald-800" : "border-red-300 bg-red-50 text-red-800"}`}>{state.message}</p> : null; }
