"use client";

import Image from "next/image";
import { useActionState, useMemo, useState } from "react";
import { ArrowDown, ArrowUp, Plus, Trash2 } from "lucide-react";
import { createProductAction, updateProductAction } from "@/actions/products";
import type { ProductEditorDto, ProductFormOption } from "@/data/products";
import { initialMutationState } from "@/types/mutation-state";

type Props = { categories: ProductFormOption[]; product?: ProductEditorDto; duplicate?: boolean };
type Size = { label: string };
type Color = { name: string; hexCode: string | null };
const inputClass = "min-h-11 w-full rounded-md border border-admin-line bg-white px-3 text-sm text-admin-ink outline-none focus:border-admin-accent focus:ring-2 focus:ring-admin-accent/20";
const labelClass = "grid gap-1.5 text-sm font-semibold text-admin-ink";

function ReorderableOptions({ kind, items, onChange }: { kind: "size" | "color"; items: (Size | Color)[]; onChange: (items: (Size | Color)[]) => void }) {
  const [label, setLabel] = useState(""); const [hex, setHex] = useState("#1a1a1a");
  function move(index: number, delta: number) { const next = [...items]; const target = index + delta; if (target < 0 || target >= next.length) return; [next[index], next[target]] = [next[target], next[index]]; onChange(next); }
  return <div className="rounded-lg border border-admin-line bg-admin-soft p-4"><p className="mb-3 text-sm font-bold text-admin-ink">{kind === "size" ? "Sizes" : "Colors"}</p><div className="mb-3 flex flex-wrap gap-2"><input className={`${inputClass} min-w-40 flex-1`} value={label} onChange={(event) => setLabel(event.target.value)} placeholder={kind === "size" ? "Add a size" : "Add a color"} />{kind === "color" ? <input aria-label="Color value" className="h-11 w-14 rounded border border-admin-line bg-white p-1" type="color" value={hex} onChange={(event) => setHex(event.target.value)} /> : null}<button className="admin-button" type="button" onClick={() => { const clean = label.trim(); if (!clean) return; onChange([...items, kind === "size" ? { label: clean } : { name: clean, hexCode: hex }]); setLabel(""); }}><Plus size={16} /> Add</button></div>{items.length ? <ul className="grid gap-2">{items.map((item, index) => { const name = "label" in item ? item.label : item.name; return <li key={`${name}-${index}`} className="flex items-center gap-2 rounded border border-admin-line bg-white px-3 py-2 text-sm text-admin-ink">{"hexCode" in item && item.hexCode ? <span className="size-4 rounded-full border" style={{ backgroundColor: item.hexCode }} /> : null}<span className="flex-1">{name}</span><button className="grid min-h-11 min-w-11 place-items-center" type="button" aria-label={`Move ${name} up`} onClick={() => move(index, -1)} disabled={index === 0}><ArrowUp size={15} /></button><button className="grid min-h-11 min-w-11 place-items-center" type="button" aria-label={`Move ${name} down`} onClick={() => move(index, 1)} disabled={index === items.length - 1}><ArrowDown size={15} /></button><button type="button" aria-label={`Remove ${name}`} className="grid min-h-11 min-w-11 place-items-center text-red-700" onClick={() => onChange(items.filter((_, itemIndex) => itemIndex !== index))}><Trash2 size={15} /></button></li>; })}</ul> : <p className="text-sm text-admin-muted">No {kind === "size" ? "sizes" : "colors"} added.</p>}</div>;
}

export function ProductForm({ categories, product, duplicate = false }: Props) {
  const action = product && !duplicate ? updateProductAction : createProductAction; const [state, formAction, pending] = useActionState(action, initialMutationState);
  const [categoryId, setCategoryId] = useState(product?.categoryId ?? categories[0]?.id ?? ""); const [subcategoryId, setSubcategoryId] = useState(product?.subcategoryId ?? ""); const [sizes, setSizes] = useState<Size[]>(product?.sizes ?? []); const [colors, setColors] = useState<Color[]>(product?.colors ?? []); const [preview, setPreview] = useState(product && !duplicate ? product.imageUrl : ""); const [originalPrice, setOriginalPrice] = useState(product?.originalPrice ?? ""); const [salePrice, setSalePrice] = useState(product?.salePrice ?? "");
  const subcategories = useMemo(() => categories.find((category) => category.id === categoryId)?.subcategories ?? [], [categories, categoryId]); const discount = Number(originalPrice) > 0 && Number(salePrice) > 0 && Number(salePrice) < Number(originalPrice) ? Math.round((1 - Number(salePrice) / Number(originalPrice)) * 100) : null; const errors = state.fieldErrors ?? {};
  return <form action={formAction} className="grid gap-6">{product && !duplicate ? <input type="hidden" name="id" value={product.id} /> : null}<input type="hidden" name="sizes" value={JSON.stringify(sizes)} /><input type="hidden" name="colors" value={JSON.stringify(colors)} />{state.message ? <div role="status" className={`rounded-md border px-4 py-3 text-sm ${state.status === "success" ? "border-emerald-300 bg-emerald-50 text-emerald-800" : "border-red-300 bg-red-50 text-red-800"}`}>{state.message}</div> : null}
    <section className="admin-panel grid gap-5"><div><h2 className="admin-section-title">Product details</h2><p className="admin-help">Keep the catalogue record focused on what customers need to shop.</p></div><div className="grid gap-4 md:grid-cols-2"><label className={labelClass}>Product name *<input className={inputClass} name="name" required maxLength={150} defaultValue={product?.name ?? ""} /></label><label className={labelClass}>Category *<select className={inputClass} name="categoryId" required value={categoryId} onChange={(event) => { setCategoryId(event.target.value); setSubcategoryId(""); }}>{categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label><label className={labelClass}>Subcategory <span className="font-normal text-admin-muted">Optional</span><select className={inputClass} name="subcategoryId" value={subcategoryId} onChange={(event) => setSubcategoryId(event.target.value)}><option value="">None</option>{subcategories.map((subcategory) => <option key={subcategory.id} value={subcategory.id}>{subcategory.name}</option>)}</select><FieldError value={errors.subcategoryId} /></label></div></section>
    <section className="admin-panel grid gap-5"><div><h2 className="admin-section-title">Product image</h2><p className="admin-help">One JPG, PNG, or WebP image, up to 5 MB.</p></div><div className="grid gap-4 sm:grid-cols-[160px_1fr]"><div className="relative aspect-[4/5] overflow-hidden rounded-md border border-admin-line bg-admin-soft">{preview ? <Image src={preview} alt="Product preview" fill sizes="160px" unoptimized={preview.startsWith("blob:")} className="object-cover" /> : <span className="grid h-full place-items-center p-4 text-center text-xs text-admin-muted">No image selected</span>}</div><label className={labelClass}>{product && !duplicate ? "Replace image (optional)" : "Product images *"}<input className={inputClass} name="image" type="file" accept="image/jpeg,image/png,image/webp" required={!product || duplicate} onChange={(event) => { const file = event.target.files?.[0]; if (file) setPreview(URL.createObjectURL(file)); }} /><FieldError value={errors.image} /></label></div></section>
    <section className="admin-panel grid gap-5"><h2 className="admin-section-title">Price and stock</h2><div className="grid gap-4 md:grid-cols-3"><label className={labelClass}>Price (PKR) *<input className={inputClass} name="originalPrice" inputMode="decimal" required value={originalPrice} onChange={(event) => setOriginalPrice(event.target.value)} /></label><label className={labelClass}>Sale price (PKR) <span className="font-normal text-admin-muted">Optional</span><input className={inputClass} name="salePrice" inputMode="decimal" value={salePrice ?? ""} onChange={(event) => setSalePrice(event.target.value)} />{discount ? <span className="font-normal text-emerald-700">Calculated discount: {discount}%</span> : null}</label><label className={labelClass}>Stock quantity *<input className={inputClass} name="stock" type="number" min="0" required defaultValue={product?.stock ?? 0} /><FieldError value={errors.stock} /></label></div></section>
    <details className="admin-panel"><summary className="cursor-pointer font-bold text-admin-ink">Options <span className="font-normal text-admin-muted">Sizes and colors</span></summary><div className="mt-5 grid gap-4 lg:grid-cols-2"><ReorderableOptions kind="size" items={sizes} onChange={(items) => setSizes(items as Size[])} /><ReorderableOptions kind="color" items={colors} onChange={(items) => setColors(items as Color[])} /></div></details>
    <section className="admin-panel grid gap-5"><h2 className="admin-section-title">Publishing</h2><div className="flex flex-wrap gap-5"><Check name="isFeatured" label="Featured" checked={duplicate ? false : product?.isFeatured} /><Check name="isNewArrival" label="New arrival" checked={duplicate ? false : product?.isNewArrival} /></div><p className="admin-help">Use Save draft or Save & publish below to control storefront visibility.</p></section>
    <div className="sticky bottom-3 flex flex-wrap justify-end gap-3 rounded-lg border border-admin-line bg-white/95 p-3 shadow-lg backdrop-blur"><button className="admin-button min-w-32" name="publish" value="false" type="submit" disabled={pending}>{pending ? "Saving…" : "Save draft"}</button><button className="admin-button min-w-36" name="publish" value="true" type="submit" disabled={pending}>{pending ? "Saving…" : "Save & publish"}</button></div>
  </form>;
}
function FieldError({ value }: { value?: string[] }) { return value?.[0] ? <span className="font-normal text-red-700">{value[0]}</span> : null; }
function Check({ name, label, checked }: { name: string; label: string; checked?: boolean }) { return <label className="flex min-h-11 items-center gap-2 text-sm font-semibold text-admin-ink"><input className="h-4 w-4 accent-admin-accent" type="checkbox" name={name} defaultChecked={checked} />{label}</label>; }
