"use client";

import Image from "next/image";
import { useActionState, useState } from "react";
import { saveSettingsAction } from "@/actions/cms";
import { initialMutationState } from "@/types/mutation-state";

export type SettingsFormValue = { brandName: string; tagline: string; proprietors: string; phone: string; whatsapp: string; email: string; instagramUrl: string | null; facebookUrl: string | null; tiktokUrl: string | null; address: string | null; googleMapsUrl: string | null; storeTiming: string | null; currency: string; lowStockThreshold: number; deliveryChargesMessage: string; whatsappGreeting: string | null; whatsappOrderStatement: string | null; websiteTitle: string; metaDescription: string | null; ogImageUrl: string | null };

export function SettingsForm({ settings }: { settings: SettingsFormValue }) {
  const [state, action, pending] = useActionState(saveSettingsAction, initialMutationState);
  const [preview, setPreview] = useState(settings.ogImageUrl ?? "");
  return <form action={action} encType="multipart/form-data" className="grid gap-6">
    <Feedback state={state} />
    <Section title="Business" help="Core identity and contact details used consistently across the website"><Grid><Field name="brandName" label="Brand Name" value={settings.brandName} required /><Field name="tagline" label="Tagline" value={settings.tagline} required /><Field name="proprietors" label="Proprietors" value={settings.proprietors} required /><Field name="phone" label="Phone" value={settings.phone} required /><Field name="whatsapp" label="WhatsApp" value={settings.whatsapp} required hint="Digits only, including country code." /><Field name="email" label="Email" type="email" value={settings.email} required /></Grid></Section>
    <Section title="Social" help="Leave a field empty to hide that social network everywhere."><Grid><Field name="instagramUrl" label="Instagram" type="url" value={settings.instagramUrl ?? ""} /><Field name="facebookUrl" label="Facebook" type="url" value={settings.facebookUrl ?? ""} /><Field name="tiktokUrl" label="TikTok" type="url" value={settings.tiktokUrl ?? ""} /></Grid></Section>
    <Section title="Store" help="Unconfigured address, map, and timings stay hidden on the public website."><Grid><Field name="address" label="Address" value={settings.address ?? ""} multiline /><Field name="storeTiming" label="Store timings" value={settings.storeTiming ?? ""} multiline /><Field name="googleMapsUrl" label="Google Maps URL" type="url" value={settings.googleMapsUrl ?? ""} hint="HTTPS Google Maps link or embed URL only." /></Grid></Section>
    <Section title="Ecommerce" help="WhatsApp creates an inquiry only; it does not record a sale."><Grid><label className="admin-label">Currency<select className="admin-input" name="currency" defaultValue="PKR"><option value="PKR">PKR</option></select></label><Field name="lowStockThreshold" label="Low stock threshold" type="number" min="0" value={String(settings.lowStockThreshold)} required /><Field name="deliveryChargesMessage" label="Delivery charges message" value={settings.deliveryChargesMessage} required /><Field name="whatsappGreeting" label="WhatsApp greeting" value={settings.whatsappGreeting ?? ""} hint="Optional. Leave empty to use the brand name in the future ordering flow." /><Field name="whatsappOrderStatement" label="Order intent statement" value={settings.whatsappOrderStatement ?? ""} hint="Optional. Do not imply that an inquiry is a completed order." /></Grid></Section>
    <Section title="SEO" help="Global defaults used when a page does not provide its own metadata."><Grid><Field name="websiteTitle" label="Website title" value={settings.websiteTitle} required /><Field name="metaDescription" label="Meta description" value={settings.metaDescription ?? ""} multiline /></Grid><div className="mt-5 grid gap-4 sm:grid-cols-[160px_1fr]"><div className="relative aspect-[1.91/1] overflow-hidden rounded-md border border-admin-line bg-admin-soft">{preview ? <Image src={preview} alt="Open Graph preview" fill sizes="160px" className="object-cover" /> : <span className="grid h-full place-items-center text-xs text-admin-muted">No OG image</span>}</div><label className="admin-label">Open Graph image<input className="admin-input" type="file" name="ogImage" accept="image/jpeg,image/png,image/webp" onChange={(event) => { const selected = event.target.files?.[0]; if (selected) setPreview(URL.createObjectURL(selected)); }} /><span className="admin-help">JPG, PNG, or WebP up to 5 MB.</span>{settings.ogImageUrl ? <span className="mt-2 flex items-center gap-2 font-normal"><input type="checkbox" name="removeOgImage" onChange={(event) => { if (event.target.checked) setPreview(""); else setPreview(settings.ogImageUrl ?? ""); }} /> Remove current image</span> : null}</label></div></Section>
    <div className="sticky bottom-3 flex justify-end rounded-lg border border-admin-line bg-white/95 p-3 shadow-lg"><button className="admin-button min-w-40" disabled={pending}>{pending ? "Saving…" : "Save settings"}</button></div>
  </form>;
}

function Section({ title, help, children }: { title: string; help: string; children: React.ReactNode }) { return <section className="admin-panel"><h2 className="admin-section-title">{title}</h2><p className="admin-help mb-5">{help}</p>{children}</section>; }
function Grid({ children }: { children: React.ReactNode }) { return <div className="grid gap-4 md:grid-cols-2">{children}</div>; }
function Field({ name, label, value, type = "text", multiline, required, min, hint }: { name: string; label: string; value: string; type?: string; multiline?: boolean; required?: boolean; min?: string; hint?: string }) { return <label className="admin-label">{label}{multiline ? <textarea className="admin-input min-h-24 py-3" name={name} defaultValue={value} required={required} /> : <input className="admin-input" name={name} type={type} defaultValue={value} required={required} min={min} />}{hint ? <span className="admin-help">{hint}</span> : null}</label>; }
function Feedback({ state }: { state: typeof initialMutationState }) { return state.message ? <p role="status" className={`rounded-md border px-4 py-3 text-sm ${state.status === "success" ? "border-emerald-300 bg-emerald-50 text-emerald-800" : "border-red-300 bg-red-50 text-red-800"}`}>{state.message}</p> : null; }
