import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Gem, Layers3, MapPin, MessageCircle, Shirt, Sparkles } from "lucide-react";

import { CinematicHero } from "@/components/storefront/cinematic-hero";
import { Container } from "@/components/storefront/container";
import { ProductCard } from "@/components/storefront/product-card";
import { getHomepageData, type StorefrontProduct } from "@/data/storefront";
import type { CmsBlockValue } from "@/types/cms";
import type { Metadata } from "next";

export const metadata: Metadata = { alternates: { canonical: "/" } };

export default async function HomePage() {
  const data = await getHomepageData();
  const block = (key: string): CmsBlockValue => data.blocks[key] ?? { fields: {} };
  const hero = block("hero");
  const heroCandidates = data.categories.map((category) => ({ url: category.bannerImageUrl || category.imageUrl, alt: `${category.name} editorial` })).filter((image): image is { url: string; alt: string } => Boolean(image.url));
  const accessories = data.categories.find((category) => category.slug === "accessories");
  return <main>
    <CinematicHero heading={hero.fields.heading || "MEN’S HUB"} tagline={hero.fields.tagline || data.settings.tagline} description={hero.fields.description || "Premium menswear, footwear and accessories crafted for the modern man."} primaryLabel={hero.fields.primaryCtaLabel || "SHOP COLLECTION"} primaryLink={hero.fields.primaryCtaLink || "/shop"} secondaryLabel={hero.fields.secondaryCtaLabel || "VIEW NEW ARRIVALS"} secondaryLink={hero.fields.secondaryCtaLink || "/new-arrivals"} mainImage={hero.imageUrl ? { url: hero.imageUrl, alt: "Men’s Hub collection" } : heroCandidates[0]} secondaryImages={heroCandidates.slice(hero.imageUrl ? 0 : 1, hero.imageUrl ? 2 : 3)} />
    <CategorySection categories={data.categories} content={block("shop-by-category")} />
    <CollectionSection eyebrow="Latest edit" content={block("new-arrivals")} fallbackHeading="New Arrivals" products={data.newProducts} href="/new-arrivals" empty="New arrivals will appear here when they are published." />
    <CollectionSection eyebrow="Limited offers" content={block("sale")} fallbackHeading="Sale / Discount Collection" products={data.saleProducts} href="/sale" empty="There are no active sale products right now." sale />
    <CollectionSection eyebrow="Selected for you" content={block("featured")} fallbackHeading="Featured Collection" products={data.featuredProducts} href="/shop?featured=yes" empty="Featured products will appear here when selected by the store." />
    <WhySection content={block("why-mens-hub")} />
    <AccessoriesSection category={accessories} content={block("accessories-spotlight")} />
    <VisitSection content={block("visit-store")} settings={data.settings} />
  </main>;
}

function SectionHeader({ eyebrow, heading, description, href }: { eyebrow: string; heading: string; description?: string; href?: string }) { return <header className="mb-9 flex flex-col gap-5 sm:mb-12 sm:flex-row sm:items-end sm:justify-between"><div><p className="store-eyebrow">{eyebrow}</p><h2 className="store-section-title">{heading}</h2>{description ? <p className="mt-3 max-w-2xl text-sm leading-7 text-muted sm:text-base">{description}</p> : null}</div>{href ? <Link className="group inline-flex min-h-11 items-center gap-2 self-start text-xs font-bold uppercase tracking-[0.16em] text-ivory hover:text-gold sm:self-auto" href={href}>View all <ArrowRight className="transition-transform group-hover:translate-x-1" size={16} /></Link> : null}</header>; }

function CategorySection({ categories, content }: { categories: Awaited<ReturnType<typeof getHomepageData>>["categories"]; content: CmsBlockValue }) { return <section className="store-section border-b border-line"><Container size="wide"><SectionHeader eyebrow="The complete wardrobe" heading={content.fields.heading || "Shop by Category"} description={content.fields.description} />{categories.length ? <div className="grid grid-cols-2 gap-3 sm:grid-cols-3 sm:gap-5 lg:grid-cols-4 xl:grid-cols-6">{categories.map((category, index) => <Link href={`/shop/${category.slug}`} key={category.id} className={`group relative min-h-0 overflow-hidden bg-surface-raised ${index === 0 || index === 5 ? "sm:col-span-2" : ""}`}><div className="relative aspect-[4/5] sm:aspect-[3/4]">{category.imageUrl ? <Image src={category.imageUrl} alt={category.name} fill sizes="(max-width: 639px) 50vw, (max-width: 1279px) 33vw, 17vw" className="object-cover transition duration-700 motion-safe:group-hover:scale-[1.035]" /> : null}<div className="absolute inset-0 bg-[linear-gradient(0deg,rgba(5,5,6,.86),transparent_62%)]" /><div className="absolute inset-x-0 bottom-0 p-4 sm:p-5"><p className="font-display text-xl font-semibold text-white sm:text-2xl">{category.name}</p>{category.description ? <p className="mt-1 line-clamp-2 text-xs leading-5 text-white/65">{category.description}</p> : null}<span className="mt-3 inline-flex items-center gap-1 text-[0.62rem] font-bold uppercase tracking-[0.16em] text-gold">Explore <ArrowRight size={13} /></span></div></div></Link>)}</div> : <EmptyState text="Categories will appear here after they are enabled." />}</Container></section>; }

function CollectionSection({ eyebrow, content, fallbackHeading, products, href, empty, sale = false }: { eyebrow: string; content: CmsBlockValue; fallbackHeading: string; products: StorefrontProduct[]; href: string; empty: string; sale?: boolean }) { return <section className={`store-section border-b border-line ${sale ? "bg-[#100d0e]" : "bg-canvas"}`}><Container size="wide"><SectionHeader eyebrow={eyebrow} heading={content.fields.heading || fallbackHeading} description={content.fields.description} href={products.length ? href : undefined} />{products.length ? <div className="grid grid-cols-2 gap-x-3 gap-y-10 sm:grid-cols-3 sm:gap-x-5 lg:grid-cols-4">{products.map((product) => <ProductCard key={product.id} product={product} />)}</div> : <EmptyState text={empty} />}</Container></section>; }

function EmptyState({ text }: { text: string }) { return <div className="border border-dashed border-line bg-surface/45 px-5 py-12 text-center sm:py-16"><Sparkles className="mx-auto text-gold" size={20} aria-hidden="true" /><p className="mx-auto mt-4 max-w-lg text-sm leading-7 text-muted">{text}</p><Link href="/shop" className="mt-5 inline-flex min-h-11 items-center text-xs font-bold uppercase tracking-[0.16em] text-ivory hover:text-gold">Browse the collection <ArrowRight className="ml-2" size={15} /></Link></div>; }

function WhySection({ content }: { content: CmsBlockValue }) { const defaults = ["Curated menswear", "Modern designs", "Complete men’s fashion range", "Convenient WhatsApp ordering", "Physical store concept"]; const icons = [Gem, Sparkles, Shirt, MessageCircle, Layers3]; const points = defaults.map((fallback, index) => content.fields[`point${index + 1}`] || fallback).filter(Boolean); return <section className="store-section border-b border-line bg-ivory text-[#161617]"><Container size="wide"><SectionHeader eyebrow="Our point of view" heading={content.fields.heading || "Why Men’s Hub"} description={content.fields.description} /><div className="grid gap-px overflow-hidden border border-black/10 bg-black/10 sm:grid-cols-2 lg:grid-cols-5">{points.map((point, index) => { const Icon = icons[index] ?? Gem; return <div key={point} className="bg-ivory p-6 sm:p-7"><Icon size={22} strokeWidth={1.5} className="text-[#8b6912]" /><p className="mt-8 font-display text-xl font-semibold leading-tight">{point}</p><span className="mt-4 block h-px w-8 bg-[#b68d22]" /></div>; })}</div></Container></section>; }

function AccessoriesSection({ category, content }: { category?: Awaited<ReturnType<typeof getHomepageData>>["categories"][number]; content: CmsBlockValue }) { if (!category) return null; const image = category.bannerImageUrl || category.imageUrl; return <section className="store-section border-b border-line"><Container size="wide"><div className="grid overflow-hidden border border-line bg-surface lg:grid-cols-[1.12fr_0.88fr]"><div className="relative min-h-[55svh] overflow-hidden bg-surface-raised">{image ? <Image src={image} alt="Accessories collection" fill sizes="(max-width: 1023px) 100vw, 58vw" className="object-cover transition duration-700 motion-safe:hover:scale-[1.025]" /> : null}</div><div className="flex flex-col justify-center p-7 sm:p-12 lg:p-16"><p className="store-eyebrow">Finishing details</p><h2 className="store-section-title">{content.fields.heading || "Accessories Spotlight"}</h2>{content.fields.description ? <p className="mt-5 text-base leading-8 text-muted">{content.fields.description}</p> : null}<Link className="store-cta-primary mt-9 self-start" href={content.fields.ctaLink || `/shop/${category.slug}`}>{content.fields.ctaLabel || "Explore Accessories"}</Link></div></div></Container></section>; }

function VisitSection({ content, settings }: { content: CmsBlockValue; settings: Awaited<ReturnType<typeof getHomepageData>>["settings"] }) { const hasStore = Boolean(settings.address || settings.googleMapsUrl || settings.storeTiming); return <section className="store-section bg-[#0e0e10]"><Container size="wide"><div className="grid gap-10 border-y border-line py-10 sm:py-14 lg:grid-cols-[1fr_auto] lg:items-center"><div><p className="store-eyebrow">Connect with us</p><h2 className="store-section-title">{content.fields.heading || "Visit Our Store"}</h2>{content.fields.description ? <p className="mt-4 max-w-2xl whitespace-pre-line text-sm leading-7 text-muted sm:text-base">{content.fields.description}</p> : !hasStore ? <p className="mt-4 max-w-2xl text-sm leading-7 text-muted sm:text-base">Speak with Men’s Hub directly for product availability and ordering assistance.</p> : null}<div className="mt-6 grid gap-2 text-sm text-muted">{settings.address ? <p className="flex items-start gap-2 whitespace-pre-line"><MapPin className="mt-0.5 shrink-0 text-gold" size={17} />{settings.address}</p> : null}{settings.storeTiming ? <p className="whitespace-pre-line">{settings.storeTiming}</p> : null}</div></div><div className="flex flex-col gap-3 min-[390px]:flex-row lg:flex-col xl:flex-row"><a className="store-cta-primary" href={`https://wa.me/${settings.whatsapp}`} target="_blank" rel="noopener noreferrer"><MessageCircle size={17} /> WhatsApp us</a>{settings.googleMapsUrl ? <a className="store-cta-secondary" href={settings.googleMapsUrl} target="_blank" rel="noopener noreferrer"><MapPin size={17} /> View map</a> : <Link className="store-cta-secondary" href="/contact">Contact us</Link>}</div></div></Container></section>; }
