ALTER TYPE "AdminAuditAction" ADD VALUE 'CATEGORY_CREATED';
ALTER TYPE "AdminAuditAction" ADD VALUE 'CATEGORY_UPDATED';
ALTER TYPE "AdminAuditAction" ADD VALUE 'CATEGORY_STATE_CHANGED';
ALTER TYPE "AdminAuditAction" ADD VALUE 'CATEGORY_REORDERED';
ALTER TYPE "AdminAuditAction" ADD VALUE 'CATEGORY_DELETED';
ALTER TYPE "AdminAuditAction" ADD VALUE 'SUBCATEGORY_CREATED';
ALTER TYPE "AdminAuditAction" ADD VALUE 'SUBCATEGORY_UPDATED';
ALTER TYPE "AdminAuditAction" ADD VALUE 'SUBCATEGORY_STATE_CHANGED';
ALTER TYPE "AdminAuditAction" ADD VALUE 'SUBCATEGORY_REORDERED';
ALTER TYPE "AdminAuditAction" ADD VALUE 'SUBCATEGORY_DELETED';

ALTER TABLE "AdminAuditLog" ADD COLUMN "entityId" TEXT;
CREATE INDEX "AdminAuditLog_entityId_createdAt_idx" ON "AdminAuditLog"("entityId", "createdAt");
