import Image from "next/image";
import Link from "next/link";

import { ProductDelete, ProductToggle } from "@/components/admin/product-actions";
import { getProductFormOptions, getProductsForAdmin } from "@/data/products";
import { requireAdmin } from "@/lib/auth/require-admin";
import { productListFilterSchema } from "@/validation/product-admin";

type Search = Record<string, string | string[] | undefined>;
const value = (search: Search, key: string) => typeof search[key] === "string" ? search[key] as string : "";

export default async function ProductsPage({ searchParams }: { searchParams: Promise<Search> }) {
  await requireAdmin();
  const search = await searchParams;
  const filters = productListFilterSchema.parse({ q: value(search, "q"), category: value(search, "category"), subcategory: value(search, "subcategory"), published: value(search, "published"), inventory: value(search, "inventory"), sale: value(search, "sale"), newArrival: value(search, "newArrival"), featured: value(search, "featured"), page: value(search, "page") || 1 });
  const [result, categories] = await Promise.all([getProductsForAdmin(filters), getProductFormOptions()]);
  const subcategories = filters.category ? categories.find((item) => item.id === filters.category)?.subcategories ?? [] : categories.flatMap((item) => item.subcategories);
  function pageHref(page: number) { const query = new URLSearchParams(); Object.entries(filters).forEach(([key, item]) => { if (item && key !== "page") query.set(key, String(item)); }); query.set("page", String(page)); return `/admin/products?${query}`; }
  return <div className="admin-page"><header className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-3xl font-bold tracking-tight text-admin-ink">Products</h1><p className="mt-1 text-sm text-admin-muted">{result.total} product{result.total === 1 ? "" : "s"} in this view.</p></div><Link className="admin-button" href="/admin/products/new">Add product</Link></header>
    <form className="admin-panel mb-5 grid gap-3 md:grid-cols-2 xl:grid-cols-4" method="get"><input className="admin-input xl:col-span-2" name="q" placeholder="Search name or SKU" defaultValue={filters.q} /><Select name="category" value={filters.category} label="All categories" options={categories.map((item) => [item.id, item.name])} /><Select name="subcategory" value={filters.subcategory} label="All subcategories" options={subcategories.map((item) => [item.id, item.name])} /><Select name="published" value={filters.published} label="Any publishing state" options={[["published", "Published"], ["unpublished", "Unpublished"]]} /><Select name="inventory" value={filters.inventory} label="Any inventory" options={[["in-stock", "In stock"], ["low-stock", "Low stock"], ["out-of-stock", "Out of stock"]]} /><Select name="sale" value={filters.sale} label="Any sale state" options={[["active", "Active sale"], ["inactive", "Not actively on sale"]]} /><div className="flex gap-2"><button className="admin-button flex-1">Apply</button><Link className="admin-button-secondary" href="/admin/products">Clear</Link></div><div className="flex flex-wrap gap-4 md:col-span-2 xl:col-span-4"><CheckFilter name="newArrival" label="New arrivals" value={filters.newArrival} /><CheckFilter name="featured" label="Featured" value={filters.featured} /></div></form>
    {result.products.length === 0 ? <div className="admin-panel py-14 text-center"><h2 className="admin-section-title">No products found</h2><p className="mt-2 text-sm text-admin-muted">Adjust the filters or add the first real product.</p></div> : <div className="grid gap-4">{result.products.map((product) => { const stock = product.availableArticles === 0 ? "OUT OF STOCK" : product.availableArticles <= result.threshold ? `ONLY ${product.availableArticles} LEFT` : "IN STOCK"; return <article key={product.id} className="admin-panel grid gap-4 md:grid-cols-[88px_minmax(0,1fr)_auto]"><div className="relative aspect-square overflow-hidden rounded-md bg-admin-soft"><Image src={product.imageUrl} alt="" fill sizes="88px" className="object-cover" /></div><div><div className="flex flex-wrap items-center gap-2"><h2 className="font-bold text-admin-ink">{product.name}</h2>{!product.isPublished ? <Tag>Draft</Tag> : null}{product.isActiveSale ? <Tag>Sale</Tag> : null}{product.isFeatured ? <Tag>Featured</Tag> : null}{product.isNewArrival ? <Tag>New</Tag> : null}</div><p className="mt-1 text-sm text-admin-muted">{product.sku} · {product.category.name}{product.subcategory ? ` / ${product.subcategory.name}` : ""}</p><p className="mt-2 text-sm font-semibold text-admin-ink">PKR {product.isActiveSale ? product.salePrice : product.originalPrice} · {stock}</p></div><div className="flex flex-wrap items-start gap-2 md:max-w-80 md:justify-end"><Link className="admin-action" href={`/admin/products/${product.id}/edit`}>Edit</Link><Link className="admin-action" href={`/admin/products/new?duplicate=${product.id}`}>Duplicate</Link><ProductToggle id={product.id} field="isPublished" value={!product.isPublished} label={product.isPublished ? "Unpublish" : "Publish"} /><ProductToggle id={product.id} field="isFeatured" value={!product.isFeatured} label={product.isFeatured ? "Unfeature" : "Feature"} /><ProductToggle id={product.id} field="isNewArrival" value={!product.isNewArrival} label={product.isNewArrival ? "Remove new" : "Mark new"} /><ProductToggle id={product.id} field="saleEnabled" value={!product.saleEnabled} label={product.saleEnabled ? "Disable sale" : "Enable sale"} /><ProductDelete id={product.id} name={product.name} /></div></article>; })}</div>}
    {result.pageCount > 1 ? <nav aria-label="Product pages" className="mt-6 flex items-center justify-between"><Link className="admin-button-secondary" href={pageHref(Math.max(1, result.page - 1))}>Previous</Link><span className="text-sm text-admin-muted">Page {result.page} of {result.pageCount}</span><Link className="admin-button-secondary" href={pageHref(Math.min(result.pageCount, result.page + 1))}>Next</Link></nav> : null}
  </div>;
}
function Select({ name, value, label, options }: { name: string; value: string; label: string; options: string[][] }) { return <select className="admin-input" name={name} defaultValue={value}><option value="">{label}</option>{options.map(([id, option]) => <option key={id} value={id}>{option}</option>)}</select>; }
function CheckFilter({ name, label, value }: { name: string; label: string; value: string }) { return <label className="flex items-center gap-2 text-sm text-admin-ink"><input type="checkbox" name={name} value="yes" defaultChecked={value === "yes"} />{label}</label>; }
function Tag({ children }: { children: React.ReactNode }) { return <span className="rounded-full bg-admin-soft px-2 py-1 text-[10px] font-bold uppercase tracking-wide text-admin-muted">{children}</span>; }
