import Image from "next/image";
import Link from "next/link";

type HeroImage = { url: string; alt: string };
type Props = { heading: string; tagline: string; description: string; primaryLabel: string; primaryLink: string; secondaryLabel: string; secondaryLink: string; mainImage?: HeroImage; secondaryImages: HeroImage[] };

export function CinematicHero(props: Props) {
  return <section className="relative -mt-[4.25rem] flex min-h-[100svh] overflow-hidden border-b border-line bg-canvas pt-[4.25rem]" aria-labelledby="hero-title"><div className="hero-light pointer-events-none absolute inset-0" aria-hidden="true" /><div className="mx-auto grid w-full max-w-[90rem] grid-cols-1 items-center gap-8 px-[var(--mh-container-gutter)] py-16 lg:grid-cols-[0.86fr_1.14fr] lg:gap-12 lg:py-20"><div className="hero-enter relative z-10 max-w-2xl"><p className="mb-5 text-xs font-bold uppercase tracking-[0.28em] text-gold">{props.tagline}</p><h1 id="hero-title" className="font-display text-[clamp(3.6rem,10vw,8.5rem)] font-semibold uppercase leading-[0.78] tracking-[-0.045em] text-ivory">{props.heading}</h1><p className="mt-8 max-w-xl text-base leading-7 text-muted sm:text-lg">{props.description}</p><div className="mt-9 flex flex-col gap-3 min-[390px]:flex-row"><Link className="store-cta-primary" href={props.primaryLink}>{props.primaryLabel}</Link><Link className="store-cta-secondary" href={props.secondaryLink}>{props.secondaryLabel}</Link></div></div><div className="relative min-h-[46svh] perspective-[1200px] lg:min-h-[76svh]"><div className="hero-image-enter absolute inset-y-0 right-0 w-[82%] overflow-hidden bg-surface-raised shadow-[0_30px_90px_rgb(0_0_0/0.5)] lg:w-[78%] lg:rotate-y-[-2deg]">{props.mainImage ? <Image src={props.mainImage.url} alt={props.mainImage.alt} fill preload sizes="(max-width: 1023px) 82vw, 45vw" className="object-cover object-center" /> : <div className="h-full bg-surface-raised" />}<div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(11,11,12,.48),transparent_48%),linear-gradient(0deg,rgba(11,11,12,.35),transparent_45%)]" aria-hidden="true" /></div>{props.secondaryImages.slice(0, 2).map((image, index) => <div key={image.url} className={`hero-card-enter absolute overflow-hidden border border-white/10 bg-surface shadow-2xl ${index === 0 ? "bottom-3 left-0 h-[38%] w-[34%]" : "right-0 top-8 h-[28%] w-[27%]"}`} style={{ animationDelay: `${350 + index * 120}ms` }}><Image src={image.url} alt={image.alt} fill sizes="(max-width: 1023px) 28vw, 14vw" className="object-cover" /></div>)}</div></div><div className="absolute bottom-5 left-1/2 hidden -translate-x-1/2 text-[0.6rem] font-bold uppercase tracking-[0.22em] text-subtle lg:block">Scroll to explore</div></section>;
}
