import Link from "next/link";
import { Container } from "@/components/storefront/container";
import { ProductCard } from "@/components/storefront/product-card";
import { ShopFilters } from "@/components/storefront/shop-filters";
import { SortSelect } from "@/components/storefront/sort-select";
import type { StorefrontProduct } from "@/data/storefront";
import type { StorefrontFilters } from "@/validation/storefront";

type CollectionData = { products: StorefrontProduct[]; categories: { id: string; name: string; slug: string; subcategories: { id: string; name: string; slug: string }[] }[]; options: { sizes: string[]; colors: string[] }; total: number; page: number; pageCount: number };
function pageHref(action: string, filters: StorefrontFilters, page: number) { const query = new URLSearchParams(); Object.entries({ ...filters, page: String(page) }).forEach(([key, value]) => { if (value) query.set(key, String(value)); }); return `${action}?${query}`; }

export function CollectionPage({ eyebrow, title, description, data, filters, action, routeCategory }: { eyebrow: string; title: string; description?: string | null; data: CollectionData; filters: StorefrontFilters; action: string; routeCategory?: string }) {
  return <main className="pb-24 pt-14 sm:pb-32 sm:pt-20"><Container size="wide"><header className="mb-9 border-b border-line pb-8"><p className="store-eyebrow">{eyebrow}</p><h1 className="font-display text-5xl font-semibold leading-none text-ivory sm:text-7xl">{title}</h1>{description ? <p className="mt-5 max-w-2xl leading-7 text-muted">{description}</p> : null}</header><div className="lg:grid lg:grid-cols-[17rem_minmax(0,1fr)] lg:gap-8"><ShopFilters action={action} filters={filters} categories={data.categories} sizes={data.options.sizes} colors={data.options.colors} routeCategory={routeCategory} /><section aria-label="Products"><div className="mb-7 flex flex-wrap items-center justify-between gap-3"><p className="text-sm text-muted">{data.total} {data.total === 1 ? "product" : "products"}{filters.q ? ` for “${filters.q}”` : ""}</p><form action={action}>{Object.entries(filters).filter(([key, value]) => key !== "sort" && key !== "page" && value).map(([key, value]) => <input key={key} type="hidden" name={key} value={String(value)} />)}<SortSelect value={filters.sort} /></form></div>{data.products.length ? <div className="grid grid-cols-2 gap-x-3 gap-y-10 sm:grid-cols-3 sm:gap-x-5 xl:grid-cols-4">{data.products.map((product) => <ProductCard key={product.id} product={product} />)}</div> : <div className="border border-dashed border-line bg-surface/50 px-5 py-16 text-center"><h2 className="font-display text-2xl text-ivory">No matching products</h2><p className="mt-3 text-sm text-muted">Try clearing a filter or check back as the collection grows.</p><Link href={action} className="store-cta-secondary mt-6">Clear filters</Link></div>}{data.pageCount > 1 ? <nav aria-label="Product pages" className="mt-14 flex justify-center gap-2">{data.page > 1 ? <Link className="store-cta-secondary" href={pageHref(action, filters, data.page - 1)}>Previous</Link> : null}<span className="flex min-h-12 items-center px-4 text-sm text-muted">Page {data.page} of {data.pageCount}</span>{data.page < data.pageCount ? <Link className="store-cta-secondary" href={pageHref(action, filters, data.page + 1)}>Next</Link> : null}</nav> : null}</section></div></Container></main>;
}
