import Image from "next/image";
import { ProductTrackedLink } from "@/components/storefront/analytics-events";
import { WishlistButton } from "@/components/storefront/wishlist-button";
import type { StorefrontProduct } from "@/data/storefront";

const currency = new Intl.NumberFormat("en-PK", { style: "currency", currency: "PKR", minimumFractionDigits: 0, maximumFractionDigits: 2 });

export function ProductCard({ product }: { product: StorefrontProduct }) {
  const stock = product.availableArticles === 0 ? "OUT OF STOCK" : product.availableArticles <= product.lowStockThreshold ? `ONLY ${product.availableArticles} LEFT` : "IN STOCK";
  const href = `/product/${product.slug}`;
  const wishlistProduct = { id: product.id, slug: product.slug, name: product.name, sku: product.sku, imageUrl: product.imageUrl, price: product.effectivePrice, availableStock: product.availableArticles, sizes: product.sizes.map((item) => item.label), colors: product.colors.map((item) => item.name), productUrl: href };
  return <article className="group min-w-0"><div className="relative aspect-[4/5] overflow-hidden bg-surface-raised"><ProductTrackedLink productId={product.id} href={href} aria-label={`View ${product.name}`} className="block h-full"><Image src={product.imageUrl} alt={product.name} fill sizes="(max-width: 639px) 50vw, (max-width: 1023px) 33vw, 25vw" className="object-cover transition duration-500 ease-out motion-safe:group-hover:scale-[1.025]" /></ProductTrackedLink><div className="absolute left-3 top-3 flex flex-wrap gap-1.5">{product.isNewArrival ? <span className="product-badge bg-gold text-gold-ink">New</span> : null}{product.isSale ? <span className="product-badge bg-critical text-white">Sale {product.discountPercent}%</span> : null}</div><WishlistButton product={wishlistProduct} className="absolute right-3 top-3" /></div><div className="pt-4"><p className="text-[0.65rem] font-bold uppercase tracking-[0.16em] text-subtle">Article {product.sku}</p><ProductTrackedLink productId={product.id} href={href} className="mt-1.5 block truncate font-display text-xl font-semibold text-ivory hover:text-gold">{product.name}</ProductTrackedLink><div className="mt-2 flex flex-wrap items-baseline gap-2"><span className="text-sm font-bold text-ivory">{currency.format(Number(product.effectivePrice))}</span>{product.isSale ? <span className="text-xs text-subtle line-through">{currency.format(Number(product.originalPrice))}</span> : null}</div><div className="mt-3 flex min-h-5 items-center justify-between gap-2"><span className={`text-[0.62rem] font-bold uppercase tracking-[0.12em] ${product.availableArticles === 0 ? "text-critical" : product.availableArticles <= product.lowStockThreshold ? "text-gold" : "text-muted"}`}>{stock}</span>{product.colors.length ? <span className="flex items-center gap-1" aria-label={`${product.colors.length} colors`}>{product.colors.slice(0, 4).map((color) => <span key={color.name} title={color.name} className="size-3 rounded-full border border-white/25" style={{ backgroundColor: color.hexCode ?? "#777" }} />)}</span> : null}</div></div></article>;
}
